# Google Cloud Build - Configuración simplificada
# Optimizado para Cloud Run desde GitHub

steps:
  # Step 1: Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/educred-app:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/educred-app:latest'
      - '.'
    timeout: 1200s

  # Step 2: Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/educred-app:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/educred-app:latest']

  # Step 3: Deploy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'educred-app'
      - '--image=gcr.io/$PROJECT_ID/educred-app:$SHORT_SHA'
      - '--region=europe-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--port=3000'

images:
  - 'gcr.io/$PROJECT_ID/educred-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/educred-app:latest'

timeout: 1800s

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
