# Google Cloud Build configuration
# Compatible with both Container Registry and Artifact Registry

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '.'
    id: 'build-image'
    timeout: 1200s

  # Step 2: Push the images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
    id: 'push-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE_NAME}:latest'
    id: 'push-latest'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_IMAGE_NAME}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL},NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--timeout'
      - '300'
    id: 'deploy-cloud-run'
    waitFor: ['push-sha']

# Images to be stored
images:
  - '${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_IMAGE_NAME}:latest'

# Build timeout
timeout: 1800s

# Substitution variables (configure in Cloud Build Triggers)
substitutions:
  # Required: Set these in your Cloud Build Trigger
  _NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your-anon-key-here'
  
  # Service configuration
  _SERVICE_NAME: 'educred-app'
  _REGION: 'us-central1'
  
  # Image name - Choose ONE option:
  # Option 1: Container Registry (gcr.io)
  _IMAGE_NAME: 'gcr.io/${PROJECT_ID}/educred-app'
  # Option 2: Artifact Registry (uncomment to use)
  # _IMAGE_NAME: '${_REGION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/educred-app'
  
  # Resource limits
  _MEMORY: '512Mi'
  _CPU: '1'
  _MAX_INSTANCES: '10'
  _MIN_INSTANCES: '0'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: 'ALLOW_LOOSE'
